### ISSUE TITLE
[FIXED] Doesn't work on KDE Wayland, while the AppImage does

### ISSUE THREAD

**Issue by pizzadude** [flathub/org.duckstation.DuckStation#3]
The official AppImage works with wayland, while this flatpak doesn't. I'm using Fedora 34 KDE with the wayland session.

When I attempt to open a game on this flatpak version, I can hear audio but nothing else happens. On the AppImage it works properly.

This is the Qt version.

**Comment by j8r** [comment]
You've tried the Qt version of the AppImage and the one of the Flatpak?

**Comment by j8r** [comment]
All should be already set-up to have a functional Wayland application: `- --socket=wayland` and  `--socket=fallback-x11` permissions, and `- -DUSE_WAYLAND=ON`.

It may be some configuration/environment variable to add on your side, I don't know yet. I'll try on my side in the following days.

**Comment by pizzadude** [comment]
> You've tried the Qt version of the AppImage and the one of the Flatpak?

Yes.

**Comment by j8r** [comment]
Have you experienced the same issue for the `-nogui` binaries?

**Comment by pizzadude** [comment]
Duckstation NoGUI AppImage doesn't load in Fedora 34 KDE because:

```error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory```

However, the flatpak nogui version works fine it seems.

**Comment by j8r** [comment]
Maybe `-DUSE_EGL=ON` has to be added, especially if you are in a Nvidia GPU - do you?

**Comment by j8r** [comment]
Done, you can try the latest releaase by updating the DuckStation flatpak in your system, which will be available in the following hours.

**Comment by pizzadude** [comment]
I'm on  a thinkpad t580 with intel hd graphics. Full specs:

```
Kernel: Linux 5.13.4-200.fc34.x86_64 x86_64
Distro: Fedora release 34 (Thirty Four)
CPU:    Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
        4 cores/threads
        3500.00 MHz
RAM:    7.60 GiB
GPU:    Mesa Intel(R) HD Graphics 620 (KBL GT2)
        OpenGL 4.6 (Compatibility Profile) Mesa 21.1.5
        GLSL 4.60
```

**Comment by pizzadude** [comment]
Note that the duckstation flatpak works fine in X11, just not Wayland.

**Comment by pizzadude** [comment]
Just updated the flatpak. Still doesn't work. But I noticed something. If I click fullscreen mode it works. It just doesn't work in windowed mode.

**Comment by j8r** [comment]
I think it the option was already on by default, so it did nothing. Now it is explicit though.

I've no other idea. Could be an issue related to the compositor (kwin) - because only triggered in windowed mode - or flatpak - or both combined.

**Comment by j8r** [comment]
I think the option was already on by default, so it did nothing. Now it is explicit though.

I've no other idea. Could be an issue related to the compositor (kwin) - because only triggered in windowed mode - or flatpak - or both combined.

**Comment by j8r** [comment]
Have you any useful application logs, like errors, related to OpenGL for example or anything else?

**Comment by pizzadude** [comment]
Nope.

**Comment by pizzadude** [comment]
@j8r I fixed it by removing "Fallback X11" and "Wayland" sockets from Duckstation via Flatseal.

**Comment by pizzadude** [comment]
Maybe this should be default in the flatpak?

**Comment by j8r** [comment]
Not sure. DuckStation is supposed to work on Wayland, didn't you say it was working with the AppImage? Or the AppImage was also using XWayland?

**Comment by pizzadude** [comment]
I tested with xeyes and it seems Duckstation AppImage is running in Xwayland.

**Comment by j8r** [comment]
What I propose:
- we can for now disable Wayland in this Flatpak, by commenting out the  "- --socket=wayland" and "- --socket=fallback-x11" lines (be free to sent a PR)
- if you can reproduce the issue with a [freshly compiled DuckStation](https://github.com/stenzek/duckstation#linux-1), then you can [open an issue at DuckStation](https://github.com/stenzek/duckstation/issues/new/choose). Otherwise, if not confirmed with a build using official build instructions, the issue won't be accepted.

**Comment by pizzadude** [comment]
The dev is not very receptive to feedback from Linux users, so I'm not sure if I want to do the second thing, but I opened a PR in this repo.

**Comment by j8r** [comment]
One more thing, do you experience the issue with both the Qt and nogui versions of DuckStation?

**Comment by pizzadude** [comment]
Just Qt version.

**Comment by j8r** [comment]
Then it'll be preferable to only disable Wayland for this one, but won't easily feasible.

I'll try to reproduce the issue when I've time, then open an issue.

For the time being the X11 only patch is fine.

**Comment by pizzadude** [comment]
Please merge https://github.com/flathub/org.duckstation.DuckStation/pull/5 because I forgot to add the x11 socket.
